name: P4 Build

on:
  workflow_call:
    secrets:
      token:
        required: true
      aws_access_key_id:
        required: true
      aws_secret_access_key:
        required: true
      slack_webhook_cicd:
        required: true
      p4user:
        required: true
      p4passwd:
        required: true
      p4port:
        required: true
    inputs:
      depot:
        type: string
        required: true
      stream:
        type: string
        required: true

defaults:
  run:
    shell: bash

jobs:
  build-p4:
    runs-on: windows-10-strong
    env:
      P4PORT:    ${{ secrets.p4port }}
      P4USER:    ${{ secrets.p4user }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.token }}

      - name: Checkout Boilerplate Project Code (Build scripts)
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.token }}
          repository: theiainteractive/boilerplate-project
          path: boilerplate-project

      - name: P4 Trust
        uses: perforce/setup-p4@v1
        with:
          command: trust
          arguments: -y

      - name: P4 Login
        uses: perforce/setup-p4@v1
        with:
          command: login
        env:
          P4PASSWD:  ${{ secrets.p4passwd }}

      - name: P4 Client Workspace
        uses: perforce/setup-p4@v1
        with:
          command: client
          arguments: -i
          spec: |
            Client:	gha-p4
            Owner:	${{ secrets.p4user }}
            Description:
              Created by ${{ secrets.p4user }}.
            Root:	gha-p4
            Options:	noallwrite noclobber nocompress unlocked modtime rmdir
            SubmitOptions:	leaveunchanged
            LineEnd:	local
            View:
              //${{ inputs.depot }}/${{ inputs.stream }}/... //gha-p4/...

      - name: P4 Sync
        uses: perforce/setup-p4@v1
        env:
          P4CLIENT: gha-p4
        with:
          command: sync
          arguments: -f

      - name: Approximate Boilerplate Project Layout
        run: |
          echo "Approximating boilerplate project repo layout..."
          mkdir src
          mv gha-p4/${{ inputs.stream }} src/
          cp -r boilerplate-project/bin .
          cp -r boilerplate-project/Makefile .

          if [ ! -f src/config.yml ]; then
            echo "name: ${{ inputs.stream }}" >> config.yml
          else
            cp src/config.yml .
          fi

      - name: Environment Variables
        run: |
          echo "Retrieving intended engine version from the .uproject file..."
          UPROJECT_FILE=`ls -1 src/${{ inputs.stream }}/*.uproject | head -n 1`
          UE_VERSION=$(jq '.EngineAssociation' $UPROJECT_FILE)

          echo "Generating development environment variables..."
          make dev ue=$UE_VERSION version=dev env=development target_platform=Win64
          make env-inject

      - name: Build
        run: |
          echo "Building ${{ inputs.stream }}..."
          make build
      
      - name: Ensure No Int/Bin in Project Plugins
        run: |
          pushd src/${{ secrets.stream }}/Plugins
            for DIR in */; do
              rm -rf $DIR/Intermediate
              rm -rf $DIR/Binaries
            done
          popd

      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.aws_access_key_id }}
      #     aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
      #     aws-region: eu-central-1
